name: Docker

on:
  push:
    branches: [ "krusta4711/request_push_messages_one_by_one", "krusta4711_request_push_messages_one_by_one" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Get version
      id: version
      run: |
        dotnet tool install --global minver-cli --version 6.0.0
        echo "version=$(minver --tag-prefix v)" >> $GITHUB_OUTPUT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: zivillian/ism7mqtt
    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: krusta/ism7mqtt_fork:test_wait_for_push
        labels: krusta/ism7mqtt_fork:test_wait_for_push
        build-args: VERSION=${{ steps.version.outputs.version }}
